# Generated by Django 4.0.1 on 2022-05-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter Name', max_length=100)),
                ('email', models.EmailField(help_text='Select Email', max_length=100)),
                ('subject', models.CharField(help_text='Enter Subject', max_length=150)),
                ('message', models.CharField(help_text='Enter Message', max_length=300)),
            ],
            options={
                'db_table': 'Ticket_details',
            },
        ),
    ]
