# Generated by Django 4.0.1 on 2022-05-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_ticketmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
