# Generated by Django 4.0.1 on 2022-05-07 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_ticketmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='user',
            field=models.ForeignKey(db_column='User_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel'),
        ),
    ]
