# Generated by Django 4.0.1 on 2022-05-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_ticketmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
